"""add payroll management foundation

Revision ID: 0a7d34f129cd
Revises: 4a920ac8fc35
Create Date: 2026-09-09 04:52:51.628933
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0a7d34f129cd"
down_revision: str | Sequence[str] | None = "4a920ac8fc35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payroll_loans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("principal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("repayment_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("repayment_frequency", sa.String(length=24), nullable=False),
        sa.Column("outstanding_balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("outstanding_balance >= 0", name="ck_payroll_loan_outstanding"),
        sa.CheckConstraint("principal > 0", name="ck_payroll_loan_principal"),
        sa.CheckConstraint("repayment_amount > 0", name="ck_payroll_loan_repayment"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_payroll_loan_org_employee_status",
        "payroll_loans",
        ["organization_id", "employee_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_loans_employee_id"), "payroll_loans", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_loans_organization_id"), "payroll_loans", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_payroll_loans_status"), "payroll_loans", ["status"], unique=False)
    op.create_table(
        "payroll_periods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_date >= start_date", name="ck_payroll_period_dates"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_payroll_period_org_name"),
    )
    op.create_index(
        "ix_payroll_period_org_dates",
        "payroll_periods",
        ["organization_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_periods_organization_id"),
        "payroll_periods",
        ["organization_id"],
        unique=False,
    )
    op.create_index(op.f("ix_payroll_periods_status"), "payroll_periods", ["status"], unique=False)
    op.create_table(
        "payroll_salary_components",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("component_kind", sa.String(length=16), nullable=False),
        sa.Column("calculation_type", sa.String(length=16), nullable=False),
        sa.Column("taxable", sa.Boolean(), nullable=False),
        sa.Column("pensionable", sa.Boolean(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("effective_start", sa.Date(), nullable=False),
        sa.Column("effective_end", sa.Date(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "calculation_type IN ('fixed', 'percentage')", name="ck_payroll_component_calc"
        ),
        sa.CheckConstraint(
            "component_kind IN ('earning', 'deduction')", name="ck_payroll_component_kind"
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_payroll_components_org_code"),
    )
    op.create_index(
        "ix_payroll_components_org_active",
        "payroll_salary_components",
        ["organization_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_components_component_kind"),
        "payroll_salary_components",
        ["component_kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_components_effective_end"),
        "payroll_salary_components",
        ["effective_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_components_effective_start"),
        "payroll_salary_components",
        ["effective_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_components_organization_id"),
        "payroll_salary_components",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "payroll_salary_structures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("basic_salary", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("effective_start", sa.Date(), nullable=False),
        sa.Column("effective_end", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("pension_participates", sa.Boolean(), nullable=False),
        sa.Column("nhf_participates", sa.Boolean(), nullable=False),
        sa.Column("paye_participates", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("change_reason", sa.String(length=1000), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint("basic_salary >= 0", name="ck_payroll_structure_basic_nonnegative"),
        sa.CheckConstraint(
            "effective_end IS NULL OR effective_end >= effective_start",
            name="ck_payroll_structure_dates",
        ),
        sa.ForeignKeyConstraint(["approved_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["employee_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "employee_id", "effective_start", name="uq_payroll_structure_start"
        ),
    )
    op.create_index(
        op.f("ix_payroll_salary_structures_effective_end"),
        "payroll_salary_structures",
        ["effective_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_structures_effective_start"),
        "payroll_salary_structures",
        ["effective_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_structures_employee_id"),
        "payroll_salary_structures",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_structures_organization_id"),
        "payroll_salary_structures",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_structures_status"),
        "payroll_salary_structures",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_payroll_structure_org_employee_effective",
        "payroll_salary_structures",
        ["organization_id", "employee_id", "effective_start", "effective_end"],
        unique=False,
    )
    op.create_table(
        "payroll_statutory_configurations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("configuration_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("effective_start", sa.Date(), nullable=False),
        sa.Column("effective_end", sa.Date(), nullable=True),
        sa.Column(
            "rules",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("change_reason", sa.String(length=1000), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "configuration_type IN ('paye', 'pension', 'nhf', 'payroll_policy')",
            name="ck_payroll_stat_type",
        ),
        sa.CheckConstraint(
            "effective_end IS NULL OR effective_end >= effective_start",
            name="ck_payroll_stat_dates",
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "configuration_type", "effective_start", name="uq_payroll_stat_start"
        ),
    )
    op.create_index(
        "ix_payroll_stat_org_type_effective",
        "payroll_statutory_configurations",
        ["organization_id", "configuration_type", "effective_start", "effective_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_statutory_configurations_configuration_type"),
        "payroll_statutory_configurations",
        ["configuration_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_statutory_configurations_effective_end"),
        "payroll_statutory_configurations",
        ["effective_end"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_statutory_configurations_effective_start"),
        "payroll_statutory_configurations",
        ["effective_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_statutory_configurations_organization_id"),
        "payroll_statutory_configurations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "payroll_adjustments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("adjustment_type", sa.String(length=24), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="ck_payroll_adjustment_amount"),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["payroll_periods.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id", "idempotency_key", name="uq_payroll_adjustment_idemp"
        ),
    )
    op.create_index(
        "ix_payroll_adjustment_org_period_employee",
        "payroll_adjustments",
        ["organization_id", "period_id", "employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_adjustments_adjustment_type"),
        "payroll_adjustments",
        ["adjustment_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_adjustments_employee_id"),
        "payroll_adjustments",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_adjustments_organization_id"),
        "payroll_adjustments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_adjustments_period_id"), "payroll_adjustments", ["period_id"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_adjustments_status"), "payroll_adjustments", ["status"], unique=False
    )
    op.create_table(
        "payroll_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("period_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("prepared_by_id", sa.Uuid(), nullable=True),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_by_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("returned_by_id", sa.Uuid(), nullable=True),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("return_reason", sa.Text(), nullable=True),
        sa.Column("paid_by_id", sa.Uuid(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "rule_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["paid_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["period_id"], ["payroll_periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["prepared_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["returned_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "period_id", name="uq_payroll_run_period"),
    )
    op.create_index(
        "ix_payroll_run_org_status", "payroll_runs", ["organization_id", "status"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_runs_approved_by_id"), "payroll_runs", ["approved_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_runs_organization_id"), "payroll_runs", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_runs_paid_by_id"), "payroll_runs", ["paid_by_id"], unique=False
    )
    op.create_index(op.f("ix_payroll_runs_period_id"), "payroll_runs", ["period_id"], unique=False)
    op.create_index(
        op.f("ix_payroll_runs_prepared_by_id"), "payroll_runs", ["prepared_by_id"], unique=False
    )
    op.create_index(op.f("ix_payroll_runs_status"), "payroll_runs", ["status"], unique=False)
    op.create_table(
        "payroll_salary_structure_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("salary_structure_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name="ck_payroll_structure_item_amount"),
        sa.CheckConstraint("percentage >= 0", name="ck_payroll_structure_item_percentage"),
        sa.ForeignKeyConstraint(
            ["component_id"], ["payroll_salary_components.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["salary_structure_id"], ["payroll_salary_structures.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "salary_structure_id", "component_id", name="uq_payroll_structure_item"
        ),
    )
    op.create_index(
        op.f("ix_payroll_salary_structure_items_component_id"),
        "payroll_salary_structure_items",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_structure_items_organization_id"),
        "payroll_salary_structure_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_salary_structure_items_salary_structure_id"),
        "payroll_salary_structure_items",
        ["salary_structure_id"],
        unique=False,
    )
    op.create_table(
        "payroll_employee_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("payroll_run_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("salary_structure_id", sa.Uuid(), nullable=True),
        sa.Column("employee_name", sa.String(length=180), nullable=False),
        sa.Column("employee_number", sa.String(length=64), nullable=True),
        sa.Column("department_name", sa.String(length=160), nullable=True),
        sa.Column("job_title", sa.String(length=120), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("basic_salary", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("allowances", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("variable_earnings", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("gross_pay", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable_pay", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("paye", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("pension_employee", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("pension_employer", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("nhf", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("loan_deductions", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("other_deductions", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("total_deductions", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("net_pay", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("employer_cost", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("proration_factor", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "calculation_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "exceptions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("payslip_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("gross_pay >= 0", name="ck_payroll_result_gross"),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["payroll_run_id"], ["payroll_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["salary_structure_id"], ["payroll_salary_structures.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payroll_run_id", "employee_id", name="uq_payroll_result_employee"),
    )
    op.create_index(
        op.f("ix_payroll_employee_results_employee_id"),
        "payroll_employee_results",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_employee_results_organization_id"),
        "payroll_employee_results",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_employee_results_payroll_run_id"),
        "payroll_employee_results",
        ["payroll_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_employee_results_salary_structure_id"),
        "payroll_employee_results",
        ["salary_structure_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_employee_results_status"),
        "payroll_employee_results",
        ["status"],
        unique=False,
    )
    op.create_index(
        "ix_payroll_result_org_employee",
        "payroll_employee_results",
        ["organization_id", "employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_payroll_result_org_status",
        "payroll_employee_results",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_table(
        "payroll_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("payroll_run_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payroll_run_id"],
            ["payroll_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payroll_history_event_type"), "payroll_history", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_history_organization_id"),
        "payroll_history",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_history_payroll_run_id"),
        "payroll_history",
        ["payroll_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_payroll_history_run_created",
        "payroll_history",
        ["payroll_run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "payroll_payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("payroll_run_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("payment_reference", sa.String(length=160), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column(
            "transaction_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("paid_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reversed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reversal_reason", sa.String(length=2000), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["finance_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paid_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payroll_run_id"],
            ["payroll_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "idempotency_key", name="uq_payroll_payment_idemp"),
        sa.UniqueConstraint("organization_id", "payroll_run_id", name="uq_payroll_payment_run"),
    )
    op.create_index(
        op.f("ix_payroll_payments_account_id"), "payroll_payments", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_payments_organization_id"),
        "payroll_payments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_payments_payroll_run_id"),
        "payroll_payments",
        ["payroll_run_id"],
        unique=False,
    )
    op.create_table(
        "payroll_loan_repayments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("loan_id", sa.Uuid(), nullable=False),
        sa.Column("payroll_result_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "posted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount > 0", name="ck_payroll_loan_repayment_amount"),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["payroll_loans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payroll_result_id"],
            ["payroll_employee_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("loan_id", "payroll_result_id", name="uq_payroll_loan_result"),
    )
    op.create_index(
        op.f("ix_payroll_loan_repayments_loan_id"),
        "payroll_loan_repayments",
        ["loan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_loan_repayments_organization_id"),
        "payroll_loan_repayments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_loan_repayments_payroll_result_id"),
        "payroll_loan_repayments",
        ["payroll_result_id"],
        unique=False,
    )
    op.create_table(
        "payroll_result_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("payroll_result_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=True),
        sa.Column("code", sa.String(length=48), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("taxable", sa.Boolean(), nullable=False),
        sa.Column("pensionable", sa.Boolean(), nullable=False),
        sa.Column("basis", sa.String(length=500), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"], ["payroll_salary_components.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["payroll_result_id"], ["payroll_employee_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payroll_result_items_category"), "payroll_result_items", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_payroll_result_items_component_id"),
        "payroll_result_items",
        ["component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_result_items_organization_id"),
        "payroll_result_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payroll_result_items_payroll_result_id"),
        "payroll_result_items",
        ["payroll_result_id"],
        unique=False,
    )
    op.create_index(
        "ix_payroll_result_items_result",
        "payroll_result_items",
        ["payroll_result_id", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payroll_result_items_result", table_name="payroll_result_items")
    op.drop_index(
        op.f("ix_payroll_result_items_payroll_result_id"), table_name="payroll_result_items"
    )
    op.drop_index(
        op.f("ix_payroll_result_items_organization_id"), table_name="payroll_result_items"
    )
    op.drop_index(op.f("ix_payroll_result_items_component_id"), table_name="payroll_result_items")
    op.drop_index(op.f("ix_payroll_result_items_category"), table_name="payroll_result_items")
    op.drop_table("payroll_result_items")
    op.drop_index(
        op.f("ix_payroll_loan_repayments_payroll_result_id"), table_name="payroll_loan_repayments"
    )
    op.drop_index(
        op.f("ix_payroll_loan_repayments_organization_id"), table_name="payroll_loan_repayments"
    )
    op.drop_index(op.f("ix_payroll_loan_repayments_loan_id"), table_name="payroll_loan_repayments")
    op.drop_table("payroll_loan_repayments")
    op.drop_index(op.f("ix_payroll_payments_payroll_run_id"), table_name="payroll_payments")
    op.drop_index(op.f("ix_payroll_payments_organization_id"), table_name="payroll_payments")
    op.drop_index(op.f("ix_payroll_payments_account_id"), table_name="payroll_payments")
    op.drop_table("payroll_payments")
    op.drop_index("ix_payroll_history_run_created", table_name="payroll_history")
    op.drop_index(op.f("ix_payroll_history_payroll_run_id"), table_name="payroll_history")
    op.drop_index(op.f("ix_payroll_history_organization_id"), table_name="payroll_history")
    op.drop_index(op.f("ix_payroll_history_event_type"), table_name="payroll_history")
    op.drop_table("payroll_history")
    op.drop_index("ix_payroll_result_org_status", table_name="payroll_employee_results")
    op.drop_index("ix_payroll_result_org_employee", table_name="payroll_employee_results")
    op.drop_index(op.f("ix_payroll_employee_results_status"), table_name="payroll_employee_results")
    op.drop_index(
        op.f("ix_payroll_employee_results_salary_structure_id"),
        table_name="payroll_employee_results",
    )
    op.drop_index(
        op.f("ix_payroll_employee_results_payroll_run_id"), table_name="payroll_employee_results"
    )
    op.drop_index(
        op.f("ix_payroll_employee_results_organization_id"), table_name="payroll_employee_results"
    )
    op.drop_index(
        op.f("ix_payroll_employee_results_employee_id"), table_name="payroll_employee_results"
    )
    op.drop_table("payroll_employee_results")
    op.drop_index(
        op.f("ix_payroll_salary_structure_items_salary_structure_id"),
        table_name="payroll_salary_structure_items",
    )
    op.drop_index(
        op.f("ix_payroll_salary_structure_items_organization_id"),
        table_name="payroll_salary_structure_items",
    )
    op.drop_index(
        op.f("ix_payroll_salary_structure_items_component_id"),
        table_name="payroll_salary_structure_items",
    )
    op.drop_table("payroll_salary_structure_items")
    op.drop_index(op.f("ix_payroll_runs_status"), table_name="payroll_runs")
    op.drop_index(op.f("ix_payroll_runs_prepared_by_id"), table_name="payroll_runs")
    op.drop_index(op.f("ix_payroll_runs_period_id"), table_name="payroll_runs")
    op.drop_index(op.f("ix_payroll_runs_paid_by_id"), table_name="payroll_runs")
    op.drop_index(op.f("ix_payroll_runs_organization_id"), table_name="payroll_runs")
    op.drop_index(op.f("ix_payroll_runs_approved_by_id"), table_name="payroll_runs")
    op.drop_index("ix_payroll_run_org_status", table_name="payroll_runs")
    op.drop_table("payroll_runs")
    op.drop_index(op.f("ix_payroll_adjustments_status"), table_name="payroll_adjustments")
    op.drop_index(op.f("ix_payroll_adjustments_period_id"), table_name="payroll_adjustments")
    op.drop_index(op.f("ix_payroll_adjustments_organization_id"), table_name="payroll_adjustments")
    op.drop_index(op.f("ix_payroll_adjustments_employee_id"), table_name="payroll_adjustments")
    op.drop_index(op.f("ix_payroll_adjustments_adjustment_type"), table_name="payroll_adjustments")
    op.drop_index("ix_payroll_adjustment_org_period_employee", table_name="payroll_adjustments")
    op.drop_table("payroll_adjustments")
    op.drop_index(
        op.f("ix_payroll_statutory_configurations_organization_id"),
        table_name="payroll_statutory_configurations",
    )
    op.drop_index(
        op.f("ix_payroll_statutory_configurations_effective_start"),
        table_name="payroll_statutory_configurations",
    )
    op.drop_index(
        op.f("ix_payroll_statutory_configurations_effective_end"),
        table_name="payroll_statutory_configurations",
    )
    op.drop_index(
        op.f("ix_payroll_statutory_configurations_configuration_type"),
        table_name="payroll_statutory_configurations",
    )
    op.drop_index(
        "ix_payroll_stat_org_type_effective", table_name="payroll_statutory_configurations"
    )
    op.drop_table("payroll_statutory_configurations")
    op.drop_index(
        "ix_payroll_structure_org_employee_effective", table_name="payroll_salary_structures"
    )
    op.drop_index(
        op.f("ix_payroll_salary_structures_status"), table_name="payroll_salary_structures"
    )
    op.drop_index(
        op.f("ix_payroll_salary_structures_organization_id"), table_name="payroll_salary_structures"
    )
    op.drop_index(
        op.f("ix_payroll_salary_structures_employee_id"), table_name="payroll_salary_structures"
    )
    op.drop_index(
        op.f("ix_payroll_salary_structures_effective_start"), table_name="payroll_salary_structures"
    )
    op.drop_index(
        op.f("ix_payroll_salary_structures_effective_end"), table_name="payroll_salary_structures"
    )
    op.drop_table("payroll_salary_structures")
    op.drop_index(
        op.f("ix_payroll_salary_components_organization_id"), table_name="payroll_salary_components"
    )
    op.drop_index(
        op.f("ix_payroll_salary_components_effective_start"), table_name="payroll_salary_components"
    )
    op.drop_index(
        op.f("ix_payroll_salary_components_effective_end"), table_name="payroll_salary_components"
    )
    op.drop_index(
        op.f("ix_payroll_salary_components_component_kind"), table_name="payroll_salary_components"
    )
    op.drop_index("ix_payroll_components_org_active", table_name="payroll_salary_components")
    op.drop_table("payroll_salary_components")
    op.drop_index(op.f("ix_payroll_periods_status"), table_name="payroll_periods")
    op.drop_index(op.f("ix_payroll_periods_organization_id"), table_name="payroll_periods")
    op.drop_index("ix_payroll_period_org_dates", table_name="payroll_periods")
    op.drop_table("payroll_periods")
    op.drop_index(op.f("ix_payroll_loans_status"), table_name="payroll_loans")
    op.drop_index(op.f("ix_payroll_loans_organization_id"), table_name="payroll_loans")
    op.drop_index(op.f("ix_payroll_loans_employee_id"), table_name="payroll_loans")
    op.drop_index("ix_payroll_loan_org_employee_status", table_name="payroll_loans")
    op.drop_table("payroll_loans")
    # ### end Alembic commands ###
