"""add leave ledger idempotency

Revision ID: 4a920ac8fc35
Revises: de70f82cef35
Create Date: 2026-09-08 01:56:34.711246
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "4a920ac8fc35"
down_revision: str | Sequence[str] | None = "de70f82cef35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "leave_balance_ledger_entries",
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
    )
    op.create_unique_constraint(
        "uq_leave_ledger_org_idempotency",
        "leave_balance_ledger_entries",
        ["organization_id", "idempotency_key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_leave_ledger_org_idempotency", "leave_balance_ledger_entries", type_="unique"
    )
    op.drop_column("leave_balance_ledger_entries", "idempotency_key")
    # ### end Alembic commands ###
