"""add leave management foundation

Revision ID: 60232000eebe
Revises: d9e2f0a5c103
Create Date: 2026-09-08 01:26:29.151996
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "60232000eebe"
down_revision: str | Sequence[str] | None = "d9e2f0a5c103"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leave_periods",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_leave_periods_org_name"),
    )
    op.create_index(
        "ix_leave_periods_org_dates",
        "leave_periods",
        ["organization_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_periods_organization_id"), "leave_periods", ["organization_id"], unique=False
    )
    op.create_table(
        "leave_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("default_entitlement", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("accrual_enabled", sa.Boolean(), nullable=False),
        sa.Column("accrual_frequency", sa.String(length=16), nullable=True),
        sa.Column("carryover_enabled", sa.Boolean(), nullable=False),
        sa.Column("carryover_limit", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("carryover_expiry_months", sa.Integer(), nullable=True),
        sa.Column("minimum_notice_days", sa.Integer(), nullable=False),
        sa.Column("maximum_consecutive_days", sa.Integer(), nullable=True),
        sa.Column("attachment_required", sa.Boolean(), nullable=False),
        sa.Column("half_day_supported", sa.Boolean(), nullable=False),
        sa.Column("eligible_employment_types", sa.Text(), nullable=True),
        sa.Column("probation_eligible", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "code", name="uq_leave_types_org_code"),
    )
    op.create_index(
        "ix_leave_types_org_active", "leave_types", ["organization_id", "is_active"], unique=False
    )
    op.create_index(
        op.f("ix_leave_types_organization_id"), "leave_types", ["organization_id"], unique=False
    )
    op.create_table(
        "leave_entitlements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("leave_type_id", sa.Uuid(), nullable=False),
        sa.Column("leave_period_id", sa.Uuid(), nullable=False),
        sa.Column("allocated_days", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["employee_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["leave_period_id"], ["leave_periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["leave_type_id"], ["leave_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "employee_id",
            "leave_type_id",
            "leave_period_id",
            name="uq_leave_entitlement_period",
        ),
    )
    op.create_index(
        op.f("ix_leave_entitlements_employee_id"),
        "leave_entitlements",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_entitlements_leave_period_id"),
        "leave_entitlements",
        ["leave_period_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_entitlements_leave_type_id"),
        "leave_entitlements",
        ["leave_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_entitlements_organization_id"),
        "leave_entitlements",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "leave_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("leave_type_id", sa.Uuid(), nullable=False),
        sa.Column("leave_period_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("duration_days", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("half_day", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reviewed_by_id", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_comment", sa.Text(), nullable=True),
        sa.Column("calendar_event_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["department_id"], ["organization_units.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["leave_period_id"], ["leave_periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["leave_type_id"], ["leave_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_requests_calendar_event_id"),
        "leave_requests",
        ["calendar_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_department_id"), "leave_requests", ["department_id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_requests_employee_id"), "leave_requests", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_leave_requests_leave_period_id"),
        "leave_requests",
        ["leave_period_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_leave_type_id"), "leave_requests", ["leave_type_id"], unique=False
    )
    op.create_index(
        "ix_leave_requests_org_employee_dates",
        "leave_requests",
        ["organization_id", "employee_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        "ix_leave_requests_org_status",
        "leave_requests",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_requests_organization_id"),
        "leave_requests",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "leave_balance_ledger_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("entitlement_id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("leave_type_id", sa.Uuid(), nullable=False),
        sa.Column("leave_period_id", sa.Uuid(), nullable=False),
        sa.Column("entry_type", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["employee_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["entitlement_id"], ["leave_entitlements.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["leave_period_id"], ["leave_periods.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["leave_type_id"], ["leave_types.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_leave_balance_ledger_entries_employee_id"),
        "leave_balance_ledger_entries",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balance_ledger_entries_entitlement_id"),
        "leave_balance_ledger_entries",
        ["entitlement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balance_ledger_entries_leave_period_id"),
        "leave_balance_ledger_entries",
        ["leave_period_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balance_ledger_entries_leave_type_id"),
        "leave_balance_ledger_entries",
        ["leave_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balance_ledger_entries_organization_id"),
        "leave_balance_ledger_entries",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_balance_ledger_entries_reference_id"),
        "leave_balance_ledger_entries",
        ["reference_id"],
        unique=False,
    )
    op.create_index(
        "ix_leave_ledger_org_employee_type_period",
        "leave_balance_ledger_entries",
        ["organization_id", "employee_id", "leave_type_id", "leave_period_id"],
        unique=False,
    )
    op.create_table(
        "leave_request_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("leave_request_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["leave_request_id"], ["leave_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_leave_history_request_created",
        "leave_request_history",
        ["leave_request_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_request_history_leave_request_id"),
        "leave_request_history",
        ["leave_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_request_history_organization_id"),
        "leave_request_history",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_leave_request_history_organization_id"), table_name="leave_request_history"
    )
    op.drop_index(
        op.f("ix_leave_request_history_leave_request_id"), table_name="leave_request_history"
    )
    op.drop_index("ix_leave_history_request_created", table_name="leave_request_history")
    op.drop_table("leave_request_history")
    op.drop_index(
        "ix_leave_ledger_org_employee_type_period", table_name="leave_balance_ledger_entries"
    )
    op.drop_index(
        op.f("ix_leave_balance_ledger_entries_reference_id"),
        table_name="leave_balance_ledger_entries",
    )
    op.drop_index(
        op.f("ix_leave_balance_ledger_entries_organization_id"),
        table_name="leave_balance_ledger_entries",
    )
    op.drop_index(
        op.f("ix_leave_balance_ledger_entries_leave_type_id"),
        table_name="leave_balance_ledger_entries",
    )
    op.drop_index(
        op.f("ix_leave_balance_ledger_entries_leave_period_id"),
        table_name="leave_balance_ledger_entries",
    )
    op.drop_index(
        op.f("ix_leave_balance_ledger_entries_entitlement_id"),
        table_name="leave_balance_ledger_entries",
    )
    op.drop_index(
        op.f("ix_leave_balance_ledger_entries_employee_id"),
        table_name="leave_balance_ledger_entries",
    )
    op.drop_table("leave_balance_ledger_entries")
    op.drop_index(op.f("ix_leave_requests_organization_id"), table_name="leave_requests")
    op.drop_index("ix_leave_requests_org_status", table_name="leave_requests")
    op.drop_index("ix_leave_requests_org_employee_dates", table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_leave_type_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_leave_period_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_employee_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_department_id"), table_name="leave_requests")
    op.drop_index(op.f("ix_leave_requests_calendar_event_id"), table_name="leave_requests")
    op.drop_table("leave_requests")
    op.drop_index(op.f("ix_leave_entitlements_organization_id"), table_name="leave_entitlements")
    op.drop_index(op.f("ix_leave_entitlements_leave_type_id"), table_name="leave_entitlements")
    op.drop_index(op.f("ix_leave_entitlements_leave_period_id"), table_name="leave_entitlements")
    op.drop_index(op.f("ix_leave_entitlements_employee_id"), table_name="leave_entitlements")
    op.drop_table("leave_entitlements")
    op.drop_index(op.f("ix_leave_types_organization_id"), table_name="leave_types")
    op.drop_index("ix_leave_types_org_active", table_name="leave_types")
    op.drop_table("leave_types")
    op.drop_index(op.f("ix_leave_periods_organization_id"), table_name="leave_periods")
    op.drop_index("ix_leave_periods_org_dates", table_name="leave_periods")
    op.drop_table("leave_periods")
    # ### end Alembic commands ###
