"""add_tasks_daily_activities

Revision ID: 897218f41206
Revises: 0035_align_schema_metadata
Create Date: 2026-09-05 09:41:33.971750
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "897218f41206"
down_revision: str | Sequence[str] | None = "0035_align_schema_metadata"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=24), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("assignee_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by_id", sa.Uuid(), nullable=True),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("meeting_id", sa.Uuid(), nullable=True),
        sa.Column("meeting_action_item_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("follow_up_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["assigned_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["department_id"], ["organization_units.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["meeting_action_item_id"], ["meeting_action_items.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("meeting_action_item_id", name="uq_tasks_meeting_action_item"),
        sa.UniqueConstraint("organization_id", "sequence", name="uq_tasks_org_sequence"),
    )
    op.create_index(op.f("ix_tasks_assigned_by_id"), "tasks", ["assigned_by_id"], unique=False)
    op.create_index(op.f("ix_tasks_assignee_id"), "tasks", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_tasks_completed_at"), "tasks", ["completed_at"], unique=False)
    op.create_index(op.f("ix_tasks_created_at"), "tasks", ["created_at"], unique=False)
    op.create_index(op.f("ix_tasks_created_by_id"), "tasks", ["created_by_id"], unique=False)
    op.create_index(op.f("ix_tasks_department_id"), "tasks", ["department_id"], unique=False)
    op.create_index(op.f("ix_tasks_due_date"), "tasks", ["due_date"], unique=False)
    op.create_index(op.f("ix_tasks_follow_up_at"), "tasks", ["follow_up_at"], unique=False)
    op.create_index(
        op.f("ix_tasks_meeting_action_item_id"), "tasks", ["meeting_action_item_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_meeting_id"), "tasks", ["meeting_id"], unique=False)
    op.create_index(
        "ix_tasks_org_assignee_status_due",
        "tasks",
        ["organization_id", "assignee_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        "ix_tasks_org_department_status_due",
        "tasks",
        ["organization_id", "department_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(op.f("ix_tasks_organization_id"), "tasks", ["organization_id"], unique=False)
    op.create_index(op.f("ix_tasks_priority"), "tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_tasks_reminder_at"), "tasks", ["reminder_at"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_team_id"), "tasks", ["team_id"], unique=False)
    op.create_table(
        "daily_activities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("meeting_id", sa.Uuid(), nullable=True),
        sa.Column("activity_date", sa.Date(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("blockers", sa.Text(), nullable=True),
        sa.Column("next_step", sa.Text(), nullable=True),
        sa.Column("visibility", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["department_id"], ["organization_units.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["meeting_id"], ["meetings.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_activities_activity_date"),
        "daily_activities",
        ["activity_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_activities_department_id"),
        "daily_activities",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_activities_meeting_id"), "daily_activities", ["meeting_id"], unique=False
    )
    op.create_index(
        "ix_daily_activities_org_department_date",
        "daily_activities",
        ["organization_id", "department_id", "activity_date"],
        unique=False,
    )
    op.create_index(
        "ix_daily_activities_org_user_date",
        "daily_activities",
        ["organization_id", "user_id", "activity_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_activities_organization_id"),
        "daily_activities",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_activities_task_id"), "daily_activities", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_activities_user_id"), "daily_activities", ["user_id"], unique=False
    )
    op.create_table(
        "task_comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_comments_author_id"), "task_comments", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_comments_organization_id"), "task_comments", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_task_comments_task_created", "task_comments", ["task_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_task_comments_task_id"), "task_comments", ["task_id"], unique=False)
    op.create_table(
        "task_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_history_actor_id"), "task_history", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_task_history_event_type"), "task_history", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_task_history_organization_id"), "task_history", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_task_history_task_created", "task_history", ["task_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_task_history_task_id"), "task_history", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_history_task_id"), table_name="task_history")
    op.drop_index("ix_task_history_task_created", table_name="task_history")
    op.drop_index(op.f("ix_task_history_organization_id"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_event_type"), table_name="task_history")
    op.drop_index(op.f("ix_task_history_actor_id"), table_name="task_history")
    op.drop_table("task_history")
    op.drop_index(op.f("ix_task_comments_task_id"), table_name="task_comments")
    op.drop_index("ix_task_comments_task_created", table_name="task_comments")
    op.drop_index(op.f("ix_task_comments_organization_id"), table_name="task_comments")
    op.drop_index(op.f("ix_task_comments_author_id"), table_name="task_comments")
    op.drop_table("task_comments")
    op.drop_index(op.f("ix_daily_activities_user_id"), table_name="daily_activities")
    op.drop_index(op.f("ix_daily_activities_task_id"), table_name="daily_activities")
    op.drop_index(op.f("ix_daily_activities_organization_id"), table_name="daily_activities")
    op.drop_index("ix_daily_activities_org_user_date", table_name="daily_activities")
    op.drop_index("ix_daily_activities_org_department_date", table_name="daily_activities")
    op.drop_index(op.f("ix_daily_activities_meeting_id"), table_name="daily_activities")
    op.drop_index(op.f("ix_daily_activities_department_id"), table_name="daily_activities")
    op.drop_index(op.f("ix_daily_activities_activity_date"), table_name="daily_activities")
    op.drop_table("daily_activities")
    op.drop_index(op.f("ix_tasks_team_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_reminder_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_organization_id"), table_name="tasks")
    op.drop_index("ix_tasks_org_department_status_due", table_name="tasks")
    op.drop_index("ix_tasks_org_assignee_status_due", table_name="tasks")
    op.drop_index(op.f("ix_tasks_meeting_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_meeting_action_item_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_follow_up_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_due_date"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_department_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_by_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_completed_at"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assignee_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assigned_by_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
