"""add leave supporting attachments

Revision ID: de70f82cef35
Revises: 60232000eebe
Create Date: 2026-09-08 01:52:26.495268
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "de70f82cef35"
down_revision: str | Sequence[str] | None = "60232000eebe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leave_attachments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("leave_request_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("storage_key", sa.String(length=1000), nullable=False),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["leave_request_id"], ["leave_requests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        op.f("ix_leave_attachments_leave_request_id"),
        "leave_attachments",
        ["leave_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_attachments_organization_id"),
        "leave_attachments",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_leave_attachments_request_created",
        "leave_attachments",
        ["leave_request_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_leave_attachments_uploaded_by_id"),
        "leave_attachments",
        ["uploaded_by_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leave_attachments_uploaded_by_id"), table_name="leave_attachments")
    op.drop_index("ix_leave_attachments_request_created", table_name="leave_attachments")
    op.drop_index(op.f("ix_leave_attachments_organization_id"), table_name="leave_attachments")
    op.drop_index(op.f("ix_leave_attachments_leave_request_id"), table_name="leave_attachments")
    op.drop_table("leave_attachments")
    # ### end Alembic commands ###
