"""add voucher finance foundation

Revision ID: f3cb669e64ff
Revises: a1c2d3e4f5a6
Create Date: 2026-09-06 09:24:05.236289
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f3cb669e64ff'
down_revision: str | Sequence[str] | None = 'a1c2d3e4f5a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_expense_categories_org_name')
    )
    op.create_index('ix_expense_categories_org_active', 'expense_categories', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_expense_categories_organization_id'), 'expense_categories', ['organization_id'], unique=False)
    op.create_table('finance_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('account_name', sa.String(length=160), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('account_type', sa.String(length=24), nullable=False),
    sa.Column('bank_name', sa.String(length=160), nullable=True),
    sa.Column('account_number_masked', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'account_code', name='uq_finance_accounts_org_code')
    )
    op.create_index(op.f('ix_finance_accounts_account_type'), 'finance_accounts', ['account_type'], unique=False)
    op.create_index('ix_finance_accounts_org_status', 'finance_accounts', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_finance_accounts_organization_id'), 'finance_accounts', ['organization_id'], unique=False)
    op.create_table('voucher_daily_sequences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_date', sa.Date(), nullable=False),
    sa.Column('next_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sequence_date')
    )
    op.create_index(op.f('ix_voucher_daily_sequences_organization_id'), 'voucher_daily_sequences', ['organization_id'], unique=False)
    op.create_table('vouchers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_number', sa.String(length=32), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('expense_category_id', sa.Uuid(), nullable=True),
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('disbursed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint('approved_amount >= 0', name='ck_vouchers_approved_nonnegative'),
    sa.CheckConstraint('disbursed_amount >= 0', name='ck_vouchers_disbursed_nonnegative'),
    sa.CheckConstraint('requested_amount >= 0', name='ck_vouchers_requested_nonnegative'),
    sa.ForeignKeyConstraint(['department_id'], ['organization_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'voucher_number', name='uq_vouchers_org_number')
    )
    op.create_index(op.f('ix_vouchers_approved_at'), 'vouchers', ['approved_at'], unique=False)
    op.create_index(op.f('ix_vouchers_created_at'), 'vouchers', ['created_at'], unique=False)
    op.create_index(op.f('ix_vouchers_department_id'), 'vouchers', ['department_id'], unique=False)
    op.create_index(op.f('ix_vouchers_expense_category_id'), 'vouchers', ['expense_category_id'], unique=False)
    op.create_index(op.f('ix_vouchers_meeting_id'), 'vouchers', ['meeting_id'], unique=False)
    op.create_index('ix_vouchers_org_department_status', 'vouchers', ['organization_id', 'department_id', 'status'], unique=False)
    op.create_index('ix_vouchers_org_requester_created', 'vouchers', ['organization_id', 'requester_id', 'created_at'], unique=False)
    op.create_index('ix_vouchers_org_status_submitted', 'vouchers', ['organization_id', 'status', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_vouchers_organization_id'), 'vouchers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vouchers_requester_id'), 'vouchers', ['requester_id'], unique=False)
    op.create_index(op.f('ix_vouchers_status'), 'vouchers', ['status'], unique=False)
    op.create_index(op.f('ix_vouchers_submitted_at'), 'vouchers', ['submitted_at'], unique=False)
    op.create_table('finance_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=True),
    sa.Column('reversal_of_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=96), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('payment_reference', sa.String(length=160), nullable=True),
    sa.Column('beneficiary', sa.String(length=240), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciliation_reference', sa.String(length=160), nullable=True),
    sa.Column('reconciliation_note', sa.String(length=2000), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_finance_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reversal_of_id'], ['finance_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_finance_transactions_org_idempotency'),
    sa.UniqueConstraint('organization_id', 'reference', name='uq_finance_transactions_org_reference')
    )
    op.create_index(op.f('ix_finance_transactions_account_id'), 'finance_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_created_by_id'), 'finance_transactions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_direction'), 'finance_transactions', ['direction'], unique=False)
    op.create_index('ix_finance_transactions_org_account_date', 'finance_transactions', ['organization_id', 'account_id', 'transaction_date'], unique=False)
    op.create_index('ix_finance_transactions_org_reconciled', 'finance_transactions', ['organization_id', 'reconciled', 'transaction_date'], unique=False)
    op.create_index('ix_finance_transactions_org_voucher', 'finance_transactions', ['organization_id', 'voucher_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_organization_id'), 'finance_transactions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_payment_reference'), 'finance_transactions', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_finance_transactions_reconciled'), 'finance_transactions', ['reconciled'], unique=False)
    op.create_index(op.f('ix_finance_transactions_reversal_of_id'), 'finance_transactions', ['reversal_of_id'], unique=True)
    op.create_index(op.f('ix_finance_transactions_transaction_date'), 'finance_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_finance_transactions_transaction_type'), 'finance_transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_finance_transactions_voucher_id'), 'finance_transactions', ['voucher_id'], unique=False)
    op.create_table('voucher_attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('url', sa.String(length=1200), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_voucher_attachments_organization_id'), 'voucher_attachments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voucher_attachments_uploaded_by_id'), 'voucher_attachments', ['uploaded_by_id'], unique=False)
    op.create_index('ix_voucher_attachments_voucher_created', 'voucher_attachments', ['voucher_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_voucher_attachments_voucher_id'), 'voucher_attachments', ['voucher_id'], unique=False)
    op.create_table('voucher_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_comments_author_id'), 'voucher_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_voucher_comments_organization_id'), 'voucher_comments', ['organization_id'], unique=False)
    op.create_index('ix_voucher_comments_voucher_created', 'voucher_comments', ['voucher_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_voucher_comments_voucher_id'), 'voucher_comments', ['voucher_id'], unique=False)
    op.create_table('voucher_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_history_actor_id'), 'voucher_history', ['actor_id'], unique=False)
    op.create_index(op.f('ix_voucher_history_event_type'), 'voucher_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_voucher_history_organization_id'), 'voucher_history', ['organization_id'], unique=False)
    op.create_index('ix_voucher_history_voucher_created', 'voucher_history', ['voucher_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_voucher_history_voucher_id'), 'voucher_history', ['voucher_id'], unique=False)
    op.create_table('voucher_line_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('expense_category_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_voucher_line_items_amount_nonnegative'),
    sa.CheckConstraint('quantity > 0', name='ck_voucher_line_items_quantity_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_voucher_line_items_tax_nonnegative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_voucher_line_items_unit_price_nonnegative'),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_line_items_expense_category_id'), 'voucher_line_items', ['expense_category_id'], unique=False)
    op.create_index(op.f('ix_voucher_line_items_organization_id'), 'voucher_line_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voucher_line_items_voucher_id'), 'voucher_line_items', ['voucher_id'], unique=False)
    op.create_index('ix_voucher_line_items_voucher_position', 'voucher_line_items', ['voucher_id', 'position'], unique=False)
    op.create_table('voucher_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voucher_reviews_decision'), 'voucher_reviews', ['decision'], unique=False)
    op.create_index(op.f('ix_voucher_reviews_organization_id'), 'voucher_reviews', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voucher_reviews_reviewer_id'), 'voucher_reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_voucher_reviews_voucher_created', 'voucher_reviews', ['voucher_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_voucher_reviews_voucher_id'), 'voucher_reviews', ['voucher_id'], unique=False)
    op.create_table('voucher_disbursements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('voucher_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('payment_reference', sa.String(length=160), nullable=True),
    sa.Column('beneficiary', sa.String(length=240), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('disbursed_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['finance_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['disbursed_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['vouchers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_voucher_disbursements_org_idempotency')
    )
    op.create_index(op.f('ix_voucher_disbursements_account_id'), 'voucher_disbursements', ['account_id'], unique=False)
    op.create_index(op.f('ix_voucher_disbursements_disbursed_by_id'), 'voucher_disbursements', ['disbursed_by_id'], unique=False)
    op.create_index(op.f('ix_voucher_disbursements_organization_id'), 'voucher_disbursements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_voucher_disbursements_transaction_id'), 'voucher_disbursements', ['transaction_id'], unique=True)
    op.create_index('ix_voucher_disbursements_voucher_date', 'voucher_disbursements', ['voucher_id', 'payment_date'], unique=False)
    op.create_index(op.f('ix_voucher_disbursements_voucher_id'), 'voucher_disbursements', ['voucher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voucher_disbursements_voucher_id'), table_name='voucher_disbursements')
    op.drop_index('ix_voucher_disbursements_voucher_date', table_name='voucher_disbursements')
    op.drop_index(op.f('ix_voucher_disbursements_transaction_id'), table_name='voucher_disbursements')
    op.drop_index(op.f('ix_voucher_disbursements_organization_id'), table_name='voucher_disbursements')
    op.drop_index(op.f('ix_voucher_disbursements_disbursed_by_id'), table_name='voucher_disbursements')
    op.drop_index(op.f('ix_voucher_disbursements_account_id'), table_name='voucher_disbursements')
    op.drop_table('voucher_disbursements')
    op.drop_index(op.f('ix_voucher_reviews_voucher_id'), table_name='voucher_reviews')
    op.drop_index('ix_voucher_reviews_voucher_created', table_name='voucher_reviews')
    op.drop_index(op.f('ix_voucher_reviews_reviewer_id'), table_name='voucher_reviews')
    op.drop_index(op.f('ix_voucher_reviews_organization_id'), table_name='voucher_reviews')
    op.drop_index(op.f('ix_voucher_reviews_decision'), table_name='voucher_reviews')
    op.drop_table('voucher_reviews')
    op.drop_index('ix_voucher_line_items_voucher_position', table_name='voucher_line_items')
    op.drop_index(op.f('ix_voucher_line_items_voucher_id'), table_name='voucher_line_items')
    op.drop_index(op.f('ix_voucher_line_items_organization_id'), table_name='voucher_line_items')
    op.drop_index(op.f('ix_voucher_line_items_expense_category_id'), table_name='voucher_line_items')
    op.drop_table('voucher_line_items')
    op.drop_index(op.f('ix_voucher_history_voucher_id'), table_name='voucher_history')
    op.drop_index('ix_voucher_history_voucher_created', table_name='voucher_history')
    op.drop_index(op.f('ix_voucher_history_organization_id'), table_name='voucher_history')
    op.drop_index(op.f('ix_voucher_history_event_type'), table_name='voucher_history')
    op.drop_index(op.f('ix_voucher_history_actor_id'), table_name='voucher_history')
    op.drop_table('voucher_history')
    op.drop_index(op.f('ix_voucher_comments_voucher_id'), table_name='voucher_comments')
    op.drop_index('ix_voucher_comments_voucher_created', table_name='voucher_comments')
    op.drop_index(op.f('ix_voucher_comments_organization_id'), table_name='voucher_comments')
    op.drop_index(op.f('ix_voucher_comments_author_id'), table_name='voucher_comments')
    op.drop_table('voucher_comments')
    op.drop_index(op.f('ix_voucher_attachments_voucher_id'), table_name='voucher_attachments')
    op.drop_index('ix_voucher_attachments_voucher_created', table_name='voucher_attachments')
    op.drop_index(op.f('ix_voucher_attachments_uploaded_by_id'), table_name='voucher_attachments')
    op.drop_index(op.f('ix_voucher_attachments_organization_id'), table_name='voucher_attachments')
    op.drop_table('voucher_attachments')
    op.drop_index(op.f('ix_finance_transactions_voucher_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_transaction_type'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_transaction_date'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_reversal_of_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_reconciled'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_payment_reference'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_organization_id'), table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_org_voucher', table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_org_reconciled', table_name='finance_transactions')
    op.drop_index('ix_finance_transactions_org_account_date', table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_direction'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_created_by_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_account_id'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index(op.f('ix_vouchers_submitted_at'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_status'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_requester_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_organization_id'), table_name='vouchers')
    op.drop_index('ix_vouchers_org_status_submitted', table_name='vouchers')
    op.drop_index('ix_vouchers_org_requester_created', table_name='vouchers')
    op.drop_index('ix_vouchers_org_department_status', table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_meeting_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_expense_category_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_department_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_created_at'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_approved_at'), table_name='vouchers')
    op.drop_table('vouchers')
    op.drop_index(op.f('ix_voucher_daily_sequences_organization_id'), table_name='voucher_daily_sequences')
    op.drop_table('voucher_daily_sequences')
    op.drop_index(op.f('ix_finance_accounts_organization_id'), table_name='finance_accounts')
    op.drop_index('ix_finance_accounts_org_status', table_name='finance_accounts')
    op.drop_index(op.f('ix_finance_accounts_account_type'), table_name='finance_accounts')
    op.drop_table('finance_accounts')
    op.drop_index(op.f('ix_expense_categories_organization_id'), table_name='expense_categories')
    op.drop_index('ix_expense_categories_org_active', table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###

